### ISSUE TITLE
Auto-refresh needed on web portal

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#22]
As the description says, the web portal (dashboard) needs to auto-refresh so that on/offline device statuses etc. update automatically without having to manually refresh the browser.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 it's already fixed. Requires the new deployment.

**Comment by doom369** [comment]
@Peterkn2001 yes, that's why we added "deployment required" which means the issue was fixed, tested, and now requires only deployment ot the cloud.
We are waiting for few more fixes and will do the deploy (1-2 days).

**Comment by doom369** [comment]
Fix deployed.

**Comment by Peterkn2001** [comment]
It's not working for me I'm afraid.

I turned TestDevice1 off 4:12pm.
The app shows Offline since 16:13, but the web browser still shows Online 15 minutes later...

![image](https://user-images.githubusercontent.com/35718564/113014197-513b3280-9174-11eb-857d-5f8501d4d4de.png)

Windows 10, Chrome browser. All browser windows were closed before starting the test, then just the Blynk web dashboard opened.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 now should be fixed.

**Comment by Peterkn2001** [comment]
No change.

The app shows the device as offline, but the web browser still shows online 10 minutes later, and the "Last Updated" date/time in the device list isn't refreshing.

Browser shows this information at the bottom...

Build Date: 16:28 31.03.2021, Commit Hash: 779020c0d3 , Commit Date: 16:24 31.03.21

Tested on Windows 10, Chrome browser.

Pete.

**Comment by Peterkn2001** [comment]
This screen....

![image](https://user-images.githubusercontent.com/35718564/113157739-14824080-9233-11eb-878b-52bc95b6d0d3.png)

Pete.

**Comment by doom369** [comment]
@Peterkn2001 strange. It works for me. Ok, we'll check few more things.

**Comment by Peterkn2001** [comment]
I noticed that the Build Date and Commit Date at the bottom of the screen had changed, so I tested it again.
The online/offline status is now updating correctly, in sync with the app.

The "Last Updated" field is remaining static though, but this is less of an issue.

Pete.

**Comment by doom369** [comment]
> The "Last Updated" field is remaining static

It's not updated in the realtime. Only status.

**Comment by Peterkn2001** [comment]
The "Last Updated" field is updated when you do a browser refresh (F5), so ought to be refreshed when the browser auto refreshes don't you think?

Pete.
