### ISSUE TITLE
Icon Button filled with solid color

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#30]
Not sure if this is intended or not please confirm.

When selecting the below options on an icon button it displays ok until placed in there on state, then it fills with a solid color. The expectation would have been the outline stayed as is and the icon just changed color. All buttons with solid color have an icon in them although this cannot be seen.

![image](https://user-images.githubusercontent.com/12146573/112894545-b87ec580-9127-11eb-89d0-ba7d3bd7fe58.png)
![image](https://user-images.githubusercontent.com/12146573/112894570-bfa5d380-9127-11eb-952d-ad0f1cad2b2e.png)
![image](https://user-images.githubusercontent.com/12146573/112894591-c5031e00-9127-11eb-80b1-7182881cc232.png)

Cheers
Ray

**Comment by alexkipar** [comment]
should be fixed in 1.0.9 build

**Comment by thomoray** [comment]
Hi have retested and can see when setting up the icons now reflects the settings mostly, but still no luck when in the device.

https://drive.google.com/file/d/1GcagMPYyjkxRrAbeOStJluOaeaJYhI3T/view?usp=sharing

**Comment by alexkipar** [comment]
@thomoray yes, the ON state is always filled.
